[package]
name = "tiny-dfr"
version = "0.3.5"
edition = "2024"
license = "MIT AND Apache-2.0"
description = "The most basic dynamic function row daemon possible"
homepage = "https://github.com/AsahiLinux/tiny-dfr"
repository = "https://github.com/AsahiLinux/tiny-dfr.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.21", default-features = false, features = [
    "freetype",
    "png",
] }
librsvg-rebind = "0.2"
drm = "0.14.1"
anyhow = "1"
input = "0.9"
libc = "0.2"
input-linux = { version = "0.7", features = ["serde"] }
input-linux-sys = "0.9"
nix = { version = "0.30", features = ["event", "signal", "inotify"] }
privdrop = "0.5.3"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
rand = "0.9"
freetype-rs = "0.38"
freedesktop-icons = "0.4.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
pure-rust-locales = "0.8"
procfs = "0.18.0"
starship-battery = "0.10.1"

[build-dependencies]
pkg-config = "0.3"

[profile.release]
lto = true
